// eslint-disable-next-line import/no-anonymous-default-export
export default {
  base: {
    remove: "Remover",
    cancel: "Cancelar",
    confirm: "Confirmar",
    insert: "Inserir",
    width: "Largura",
    height: "Altura",
  },
  controls: {
    clear: "Limpar",
    undo: "Desfazer",
    redo: "Refazer",
    fontSize: "Tamanho da Fonte",
    color: "Cor",
    textColor: "Texto",
    tempColors: "Temp Colors",
    backgroundColor: "Cor de Fundo",
    bold: "Negrito",
    lineHeight: "Altura da Linha",
    letterSpacing: "Espaçamento entre Letras",
    textIndent: "Identação de Texto",
    increaseIndent: "Aumentar Identação",
    decreaseIndent: "Diminuir Identção",
    italic: "Itálico",
    underline: "Sublinhado",
    strikeThrough: "Riscado",
    fontFamily: "Família da Fonte",
    textAlign: "Alinhamento de Texto",
    alignLeft: "Alinhamento à Esquerda",
    alignCenter: "Alinhamento Centralizado",
    alignRight: "Alinhamento à Direita",
    alignJustify: "Alinhamento Justificado",
    floatLeft: "Flutuação à Esquerda",
    floatRight: "Flutuação à Direita",
    superScript: "Sobrescrito",
    subScript: "Subscrito",
    removeStyles: "Remover Estilos",
    headings: "Cabeçalhos",
    header: "Cabeçalho",
    normal: "Normal",
    orderedList: "Lista Ordenada",
    unorderedList: "Lista Não Ordenada",
    blockQuote: "Citação",
    code: "Código",
    link: "Link",
    unlink: "Remover Link",
    hr: "Linha Horizontal",
    media: "Mídia",
    mediaLibirary: "Biblioteca de Mídia",
    confirmInsert: "teste",
    emoji: "Emoji",
    fullscreen: "Tela Cheia",
    exitFullscreen: "Sair de Tela Cheia",
  },
  linkEditor: {
    textInputPlaceHolder: "Insira o texto do link",
    linkInputPlaceHolder: "Insira a URL do link",
    inputWithEnterPlaceHolder: "Insira a URL do link e aperte Enter",
    openInNewWindow: "Abrir em nova janela",
    removeLink: "Remover Link",
  },
  audioPlayer: {
    title: "Tocar Áudio",
  },
  videoPlayer: {
    title: "Tocar Vídeo",
    embedTitle: "Mídia Embutida",
  },
  media: {
    image: "Imagem",
    video: "Vídeo",
    audio: "Áudio",
    embed: "Embutido",
  },
  remove: "Remover",
  cancel: "Cancelar",
  confirm: "Confirmar",
  insert: "Inserir Itens Selecionados",
  width: "Comprimento",
  height: "Altura",
  image: "Imagem",
  video: "Video",
  audio: "Audio",
  embed: "Embed",
  caption: "Biblioteca de Mídia",
  dragTip: "Clique ou Arraste Arquivos Aqui",
  dropTip: "Upload",
  selectAll: "Selecionar Tudo",
  deselect: "Desassociar",
  removeSelected: "Remover Itens Selecionados",
  externalInputPlaceHolder: "URL",
  externalInputTip:
    'Divida o nome da fonte e o URL da fonte com "|" e confirme pressionando Enter.',
  addLocalFile: "Adicione um Arquivo Local",
  addExternalSource: "Adicione um Link Externo",
  unnamedItem: "Remover Nome Item",
  confirmInsert: "Inserir Itens Selecionados",
};
